### ISSUE TITLE
question: help on using structlog and dictConfig 

### ISSUE THREAD

**Issue by nskalis** [hynek/structlog#184]
hi,

i am trying to use `structlog` according to the docs, but i fail to make it working:

* **catalog.py**
```python
import os
import yaml
import logging.config
import structlog
with open(
    "{}/ip-spotlight/config/{}".format(
        os.environ["DIR_BASE"], "logger.api.catalog.yaml"
    ),
    "rt",
) as f:
    logging.config.dictConfig(yaml.safe_load(f.read()))
structlog.configure(
    processors=[
        structlog.stdlib.filter_by_level,
        structlog.stdlib.add_logger_name,
        structlog.stdlib.add_log_level,
        structlog.stdlib.PositionalArgumentsFormatter(),
        structlog.processors.StackInfoRenderer(),
        structlog.processors.format_exc_info,
        structlog.processors.UnicodeDecoder(),
        structlog.stdlib.render_to_log_kwargs,
    ],
    context_class=dict,
    logger_factory=structlog.stdlib.LoggerFactory(),
    wrapper_class=structlog.stdlib.BoundLogger,
    cache_logger_on_first_use=True,
)
logger = structlog.get_logger("catalog")

import responder
import schemas
import auth
...
```

* **logger.api.catalog.yaml**
```yaml
---


  version: 1
  disable_existing_loggers: False


  formatters:

    simple:
      format: '%(asctime)s | %(levelname)s | %(process)d | %(module)s | %(funcName)s | %(message)s'


  handlers:

    console:
      class: logging.StreamHandler
      level: INFO
      formatter: simple
      stream: ext://sys.stdout

    logfile:
      class: logging.FileHandler
      level: INFO
      formatter: simple
      encoding: utf8
      filename: /var/log/ip-spotlight/ip-spotlight.api.catalog.log


  loggers:

    catalog:
      propagate: no
      level: INFO
      handlers:
        - logfile


  root:
    level: WARNING
    handlers:
      - logfile
```

* **auth.py**
```python
import structlog
logger = structlog.get_logger("catalog")

def uim(username, password, application):
...
    logger.info("assigning ldap roles", username="username")#, roles=roles)
    return roles
```

the log produced is
```
2018-10-23 23:26:40,915 | INFO | 30051 | _base | _proxy_to_logger | assigning ldap roles
```

could you please advise what i am doing wrong ?
