### ISSUE TITLE
Logging behavior when root logger level is not set

### ISSUE THREAD

**Issue by sjiekak** [hynek/structlog#494]
What is structlog behavior when root logging level is not set ?
- When I do not set `logging` root logger level, logging with warning shows up, logging with info do not show up.
- When I do set the logger level (even to `NOTSET`), logging behaves as expected

I use [logging.config.dictConfig](https://docs.python.org/3/library/logging.config.html#logging.config.dictConfig)

```yaml
version: 1
root:
  level: DEBUG
  handlers:
   - console
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: generic
    stream: "ext://sys.stderr"
formatters:
  generic:
    format: "%(message)s"
```
 
I've configured structlog with 

```python
processors = [
    structlog.stdlib.filter_by_level,
    structlog.contextvars.merge_contextvars,
    structlog.stdlib.add_log_level,
    structlog.processors.format_exc_info,
    structlog.stdlib.PositionalArgumentsFormatter(),
    structlog.processors.TimeStamper(fmt="iso"),
    structlog.processors.StackInfoRenderer(),
    structlog.processors.UnicodeDecoder(),
    structlog.stdlib.ProcessorFormatter.wrap_for_formatter,
]

structlog.configure(
            processors,
            context_class=dict,
            logger_factory=structlog.stdlib.LoggerFactory(),
            wrapper_class=structlog.stdlib.BoundLogger,
            cache_logger_on_first_use=True,
        )
```
